config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from illuminate.analytics.views import home_view
from django.views.static import serve

urlpatterns = [
    url(r'^$', view=home_view, name='home'),
    url(r'^base/$', TemplateView.as_view(template_name='base.html'), name='about'),

    # apps
    url(r'^form/', include(('illuminate.forms.urls', 'forms'), namespace='form')),
    url(r'^analytics/', include(('illuminate.analytics.urls', 'analytics'), namespace='analytics')),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include(('illuminate.users.urls', 'users'), namespace='users')),
    url(r'^accounts/', include('allauth.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
        url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

illuminate/analytics/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(
        regex=r'^user/$',
        view=views.user_anlaytics,
        name='user_analytics'
    ),
    url(
        regex=r'^lc/(?P<office_name>.+)/$',
        view=views.lc_analytics,
        name='lc_analytics'
    ),

]

illuminate/forms/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(
        regex=r'^complaint/$',
        view=views.create_complaint,
        name='create_complaint'
    ),
    url(
        regex=r'^request/$',
        view=views.create_request,
        name='create_request'
    ),
    url(
        regex=r'^case/$',
        view=views.create_case,
        name='create_case'
    ),
    url(
        regex=r'^ticket/$',
        view=views.tickets_list,
        name='ticket_list'
    ),
    url(
        regex=r'^edit/ticket/complaint/(?P<pk>[0-9]+)/$',
        view=views.ComplaintUpdate.as_view(),
        name='edit_complaint'
    ),
    url(
        regex=r'^edit/ticket/request/(?P<pk>[0-9]+)/$',
        view=views.RequestUpdate.as_view(),
        name='edit_request'
    ),
    url(
        regex=r'^edit/ticket/case/(?P<pk>[0-9]+)/$',
        view=views.CaseUpdate.as_view(),
        name='edit_case'
    ),
]

illuminate/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),

]

illuminate/analytics/models.py
from django.db import models

# Create your models here.

illuminate/core/models.py
from django.db import models

# Create your models here.

illuminate/forms/admin.py
from django.contrib import admin

from .forms import ComplaintForm
from .models import *


class TicketAdmin(admin.ModelAdmin):
    list_display = ('ticket_type', 'program', 'timestamp')
    form = ComplaintForm



admin.site.register(Ticket)
admin.site.register(Position)
admin.site.register(Office)
admin.site.register(Role)
admin.site.register(Ep)
admin.site.register(Filler)



# class RequestAdmin(admin.ModelAdmin):
#     list_display = ['full_name', 'lc', 'position', 'role',
#                   'ep_name', 'ep_entity', 'ep_email','ep_lc','ep_id','opp_id',
#                   'requested_break','program','request_Reason',
#                   "timestamp","updated"]
#     form = RequestForm
#     class Meta:
#         model = Request
#
#
# admin.site.register(Request)

illuminate/forms/apps.py
from django.apps import AppConfig


class ComplaintsConfig(AppConfig):
    name = 'illuminate.forms'

illuminate/forms/population_script.py
from illuminate.forms.create_token import GIS
from illuminate.forms.models import Position, Role, Office
import requests


def delete_everything():

    Position.objects.all().delete()
    print("Positions Deleted")
    Role.objects.all().delete()
    print("Roles Deleted")
    Office.objects.all().delete()
    print("Offices Deleted")
    # Standard.objects.all().delete()
    # print("Standards Deleted")


# def populate_standards():
#
#     Standard(name='Personal Goal Setting', number='1').save()
#     Standard(name='Outgoing Preparation Seminar', number='2').save()
#     Standard(name='Expectation Setting', number='3').save()
#     Standard(name='Incoming Preparation Seminar', number='4').save()
#     Standard(name='Development Spaces', number='5').save()
#     Standard(name='Debrief With AIESEC Home', number='6').save()
#     Standard(name='Visa And Work Permit Information', number='7').save()
#     Standard(name='Arrival Pickup', number='8').save()
#     Standard(name='Departure Support', number='9').save()
#     Standard(name='Job Description Information', number='10').save()
#     Standard(name='Duration', number='11').save()
#     Standard(name='Working Hours', number='12').save()
#     Standard(name='First Day of Work', number='13').save()
#     Standard(name='Insurance', number='14').save()
#     Standard(name='Accommodation', number='15').save()
#     Standard(name='Basic Living Cost', number='16').save()
#
#     print("Standards Populated")
#

def populate_positions():

    Position(name='MCP').save()
    Position(name='MCVP').save()
    Position(name='LCP').save()
    Position(name='LCVP').save()
    Position(name='NST').save()
    Position(name='Team Leader').save()
    Position(name='Coordinator').save()
    Position(name='Member').save()
    print("Positions Populated")


def populate_role():

    Role(name='IGV').save()
    Role(name='IGE').save()
    Role(name='IGT').save()
    Role(name='OGV').save()
    Role(name='OGE').save()
    Role(name='OGT').save()
    Role(name='F&L').save()
    Role(name='TM').save()
    Role(name='IM').save()
    Role(name='Marketing').save()
    Role(name='PD').save()
    print("Roles Populated")


def populate_offices():
    print("Populaing Offices...")
    id = "1609"
    call = GIS()
    access_token = call.generate_token()
    print(access_token)
    url = 'https://gis-api.aiesec.org/v2/committees/' + id + '.json?access_token=' + access_token
    r = requests.get(url).json()
    for i in range(0, 23):
        name = r['suboffices'][i]['name']
        office_id = r['suboffices'][i]['id']
        Office(office_name=name).save()
        Office(office_id=office_id).save()
    print("Offices Populated")


def populate_all():

    populate_role()
    populate_positions()
    populate_offices()
    # populate_standards()


populate_all()

illuminate/analytics/views.py
from django.shortcuts import render, redirect
import django.db.models
from illuminate.forms.models import *

def user_anlaytics(request):

    # initiation data
    offices = Office.objects.order_by('office_name')
    current_user = request.user
    current_user_manager = request.user.manager
    total_tickets = Ticket.objects.all()
    team_tickets = total_tickets.filter(ecb_responsible__manager__name=current_user_manager)
    user_tickets = total_tickets.filter(ecb_responsible=current_user)

    # total absolute numbers
    total_tickets_count = total_tickets.count()
    total_complaints_count = total_tickets.filter(ticket_type='Complaint').count()
    total_requests_count = total_tickets.filter(ticket_type='Request').count()
    total_cases_count = total_tickets.filter(ticket_type='Case').count()


    # Team absolute numbers
    team_tickets_count = team_tickets.count()
    team_complaints_count = team_tickets.filter(ticket_type='Complaint').count()
    team_requests_count = team_tickets.filter(ticket_type='Request').count()
    team_cases_count = team_tickets.filter(ticket_type='Case').count()


    # user absolute numbers
    user_tickets_count = user_tickets.count()
    user_complaints_count = user_tickets.filter(ticket_type='Complaint').count()
    user_complaints_count_open = user_tickets.filter(ticket_type='Complaint', ticket_state='Open').count()
    user_complaints_count_in_progress = user_tickets.filter(ticket_type='Complaint', ticket_state='In Progress').count()
    user_complaints_count_closed = user_tickets.filter(ticket_type='Complaint', ticket_state='Closed').count()

    user_requests_count = user_tickets.filter(ticket_type='Request').count()
    user_requests_count_open = user_tickets.filter(ticket_type='Request', ticket_state='Open').count()
    user_requests_count_in_progress = user_tickets.filter(ticket_type='Request', ticket_state='In Progress').count()
    user_requests_count_closed = user_tickets.filter(ticket_type='Request', ticket_state='Closed').count()

    user_cases_count = user_tickets.filter(ticket_type='Case').count()
    user_cases_count_open = user_tickets.filter(ticket_type='Case', ticket_state='Open').count()
    user_cases_count_in_progress = user_tickets.filter(ticket_type='Case', ticket_state='In Progress').count()
    user_cases_count_closed = user_tickets.filter(ticket_type='Case', ticket_state='Closed').count()

    # user relative numbers
    # total_Complaint_contribution = (user_complaints_count/total_complaints_count)*100


    context = {
        "offices": offices,
        "current_user": current_user,
        "current_user_manager": current_user_manager,
        "tickets": total_tickets,
        "user_tickets": user_tickets,

        # total absolute numbers
        "total_tickets_count": total_tickets_count,
        "total_complaints_count": total_complaints_count,
        "total_requests_count": total_requests_count,
        "total_cases_count": total_cases_count,

        # Team absolute numbers
        "team_tickets_count": team_tickets_count,
        "team_complaints_count": team_complaints_count,
        "team_requests_count": team_requests_count,
        "team_cases_count": team_cases_count,

        # user absolute numbers
        "user_tickets_count": user_tickets_count,

        "user_complaints_count": user_complaints_count,
        "user_complaints_count_open": user_complaints_count_open,
        "user_complaints_count_in_progress": user_complaints_count_in_progress,
        "user_complaints_count_closed": user_complaints_count_closed,

        "user_requests_count": user_requests_count,
        "user_requests_count_open": user_requests_count_open,
        "user_requests_count_in_progress": user_requests_count_in_progress,
        "user_requests_count_closed": user_requests_count_closed,

        "user_cases_count": user_cases_count,
        "user_cases_count_open": user_cases_count_open,
        "user_cases_count_in_progress": user_cases_count_in_progress,
        "user_cases_count_closed": user_cases_count_closed,

        # "total_Complaint_contribution": total_Complaint_contribution,

    }

    return render(request, 'analytics/user_analytics.html', context=context)


def lc_analytics(request, office_name):
    tickets = Ticket.objects.all()
    # complaints = Ticket.objects.filter(ticket_type='Complaint')
    # my_lc = Office.objects.get(pk=office_name)
    # lc = OfficeSnapshot.objects.get(office=my_lc)
    #
    offices = Office.objects.order_by('office_name')

    my_lc = Office.objects.get(pk=office_name)

    lc = Office.objects.get(office_name=my_lc)
    lc_name = my_lc.office_name
    lc_complaints_count = Ticket.objects.filter(ticket_type='Complaint', office__office_name=office_name).count()

    context = {
        "offices": offices,
        "lc_complaints_count": lc_complaints_count,
        "lc_name": lc_name,
        "lc": lc,
        "my_lc": my_lc,
        # "office": office,
    }

    return render(request, "analytics/lc_analytics.html", context)


def home_view(request):

    if request.user.is_authenticated():

        offices = Office.objects.order_by('office_name')
        tickets = Ticket.objects.all()

        current_user = request.user

        user = Ticket.objects.filter(ecb_responsible=current_user)

        # complaints data
        user_complaints_count = tickets.filter(ticket_type='Complaint').count()
        user_complaints_count_open = tickets.filter(ticket_type='Complaint', ticket_state='Open').count()
        user_complaints_count_in_progress = tickets.filter(ticket_type='Complaint', ticket_state='In Progress').count()
        user_complaints_count_closed = tickets.filter(ticket_type='Complaint', ticket_state='Closed').count()

        # requests data
        user_requests_count = tickets.filter(ticket_type='Request').count()
        user_requests_count_open = tickets.filter(ticket_type='Request', ticket_state='Open').count()
        user_requests_count_in_progress = tickets.filter(ticket_type='Request', ticket_state='In Progress').count()
        user_requests_count_closed = tickets.filter(ticket_type='Request', ticket_state='Closed').count()

        # cases data
        user_cases_count = tickets.filter(ticket_type='Case').count()
        user_cases_count_open = tickets.filter(ticket_type='Case', ticket_state='Open').count()
        user_cases_count_in_progress = tickets.filter(ticket_type='Case', ticket_state='In Progress').count()
        user_cases_count_closed = tickets.filter(ticket_type='Case', ticket_state='Closed').count()

        context = {
            "offices": offices,
            "tickets": tickets,
            "user_complaints_count": user_complaints_count,
            "user_requests_count": user_requests_count,
            "user_cases_count": user_cases_count,

            "user_complaints_count_open": user_complaints_count_open,
            "user_complaints_count_in_progress": user_complaints_count_in_progress,
            "user_complaints_count_closed": user_complaints_count_closed,
            "user_requests_count_open": user_requests_count_open,
            "user_requests_count_in_progress": user_requests_count_in_progress,
            "user_requests_count_closed": user_requests_count_closed,
            "user_cases_count_open": user_cases_count_open,
            "user_cases_count_in_progress": user_cases_count_in_progress,
            "user_cases_count_closed": user_cases_count_closed,
        }

        return render(request, "pages/home.html", context)
    else:
        return redirect("accounts/login")

illuminate/core/views.py
from django.shortcuts import render

illuminate/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView
from requests import request
from .models import User
from django.shortcuts import render


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', 'number', 'position', 'sector', 'image']

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):

        model = User

        # These next two lines tell the view to index lookups by username
        slug_field = 'username'
        slug_url_kwarg = 'username'

illuminate/templates/users/admin_user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}

  <div class="container">
    <div class="span3 well">

      <center>
        <img class="img-circle"  src={{ object.image.url }}  width="200" height="200">
          <h3>{{ object.name }}</h3>
          <p>({{ object.username }})</p>

          <form class="form-check-inline" method="post" action="{% url 'users:adminupdate' %}">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="control-group">
              <div class="controls">
                <button type="submit" class="btn btn-primary">Update</button>
              </div>
            </div>
          </form>
      </center>
    </div>
  </div>
{% endblock %}

illuminate/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}

<!------ Include the above in your HEAD tag ---------->

<div class="container">
    <div class="span3 well">
      <center>

          <img class="rounded-circle"  src={{ object.image.url }}  width="200" height="200">
        <h3>{{ object.name }}</h3>
        <p>({{ object.username }})</p>

        <p>
          <span align="left"><strong>Number:</strong></span>
          <span>{{ object.number }}</span>
        </p>
        <p>
          <span align="left"><strong>Position:</strong></span>
          <span>{{ object.position }}</span>
        </p>
        <p>
          <span align="left"><strong>Sector:</strong></span>
          <span>{{ object.sector }}</span>
        </p>

        {% if object == request.user or request.user.position == "Chair" %}
          <!-- Action buttons -->
          <div class="row">

            <div class="col-sm-12">
              <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">Edit Account</a>
              <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
              <!-- Your Stuff: Custom user template urls -->
            </div>

          </div>
          <!-- End Action buttons -->
        {% endif %}

		  </center>
    </div>
</div>




{#{% block title %}User: {{ object.username }}{% endblock %}#}
{##}
{#{% block content %}#}
{#<div class="container">#}
{##}
{#  <div class="row">#}
{#    <div class="col-sm-12">#}
{#      <img src={{ object.image.url }} height="200" width="200">#}
{#      <h2>{{ object.username }}</h2>#}
{#      <h5>Name:</h5>#}
{#        <p>{{ object.name }}</p>#}
{#      <h5>Number:</h5>#}
{#        <p>{{ object.number }}</p>#}
{#      <h5>Position:</h5>#}
{#        <p>{{ object.position }}</p>#}
{#      <h5>Sector:</h5>#}
{#        <p>{{ object.sector }}</p>#}
{##}
{#    </div>#}
{#  </div>#}
{##}
{#{% if object == request.user %}#}
{#<!-- Action buttons -->#}
{#<div class="row">#}
{##}
{#  <div class="col-sm-12">#}
{#    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>#}
{#    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>#}
{#    <!-- Your Stuff: Custom user template urls -->#}
{#  </div>#}
{##}
{#</div>#}
{#<!-- End Action buttons -->#}
{#{% endif %}#}
{##}
{##}
{#</div>#}
{% endblock content %}

illuminate/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ object.username }}{% endblock %}

{% block content %}

  <div class="container">
    <div class="span3 well">

      <center>
        <img class="img-circle"  src={{ object.image.url }}  width="200" height="200" >
          <h3>{{ object.name }}</h3>
          <p>({{ object.username }})</p>

          <form class="form-group" method="post" action="{% url 'users:update' %}">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="control-group">
              <div class="controls">
                <button type="submit" class="btn btn-primary">Update</button>
              </div>
            </div>
          </form>
      </center>
    </div>
  </div>
{% endblock %}

illuminate/templates/users/user_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}


<div class="container">
    <div class="span1 well">
      <center>
        <h2>Users</h2>

        <div class="table">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>Name</th>
                <th>Position</th>
                <th>Sector</th>
              </tr>
            </thead>
              <tbody>
              {% for user in user_list %}
{#                {% ifequal user.position  "" %}#}

                  <tr>
                    <td><a href="#aboutModal" data-toggle="modal" data-target="#{{ user.username }}Modal">{{ user.username }}</a></td>
                    <td>{{ user.position }}</td>
                    <td>{{ user.sector }}</td>
                  </tr>
                <!-- Modal -->
                <div class="modal fade" id="{{ user.username }}Modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle"><strong>More About {{ user.name }}</strong></h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                       <center>
                        <img class="img-circle"  src={{ user.image.url }}  width="150" height="150" ></a>
                        <h3 class="media-heading">{{ user.name }}</h3>
                          <p>({{ user.username }})</p>
                          <div id="left">
                            <span><strong>Number: </strong></span>
                            <span>{{ user.number }}</span>
                          </div>
                        <span><strong>Position: </strong></span>
                            <span>{{ user.position }}</span>
                        <br>
                      </center>
                      </div>
                      <div class="modal-footer">
                        <a class="btn btn-primary" href="{% url 'users:detail' user.username %}" role="button">view Account</a>
                      </div>
                    </div>
                  </div>
                </div>

{#                {% endifequal %}#}
              {% endfor %}
              </tbody>
        </table>
        </div>
      </center>
    </div>
</div>

{% endblock content %}