config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from illuminate.analytics.views import home_view
from django.views.static import serve

urlpatterns = [
    url(r'^$', view=home_view, name='home'),
    url(r'^base/$', TemplateView.as_view(template_name='base.html'), name='about'),

    # apps
    url(r'^form/', include(('illuminate.forms.urls', 'forms'), namespace='form')),
    url(r'^analytics/', include(('illuminate.analytics.urls', 'analytics'), namespace='analytics')),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include(('illuminate.users.urls', 'users'), namespace='users')),
    url(r'^accounts/', include('allauth.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
        url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

illuminate/analytics/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(
        regex=r'^user/$',
        view=views.user_anlaytics,
        name='user_analytics'
    ),
    url(
        regex=r'^lc/(?P<office_name>.+)/$',
        view=views.lc_analytics,
        name='lc_analytics'
    ),

]

illuminate/forms/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(
        regex=r'^complaint/$',
        view=views.create_complaint,
        name='create_complaint'
    ),
    url(
        regex=r'^request/$',
        view=views.create_request,
        name='create_request'
    ),
    url(
        regex=r'^case/$',
        view=views.create_case,
        name='create_case'
    ),
    url(
        regex=r'^ticket/$',
        view=views.tickets_list,
        name='ticket_list'
    ),
    url(
        regex=r'^edit/ticket/complaint/(?P<pk>[0-9]+)/$',
        view=views.ComplaintUpdate.as_view(),
        name='edit_complaint'
    ),
    url(
        regex=r'^edit/ticket/request/(?P<pk>[0-9]+)/$',
        view=views.RequestUpdate.as_view(),
        name='edit_request'
    ),
    url(
        regex=r'^edit/ticket/case/(?P<pk>[0-9]+)/$',
        view=views.CaseUpdate.as_view(),
        name='edit_case'
    ),
]

illuminate/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),

]

illuminate/analytics/models.py
from django.db import models

# Create your models here.

illuminate/core/models.py
from django.db import models

# Create your models here.

illuminate/forms/admin.py
from django.contrib import admin

from .forms import ComplaintForm
from .models import *


class TicketAdmin(admin.ModelAdmin):
    list_display = ('ticket_type', 'program', 'timestamp')
    form = ComplaintForm



admin.site.register(Ticket)
admin.site.register(Position)
admin.site.register(Office)
admin.site.register(Role)
admin.site.register(Ep)
admin.site.register(Filler)



# class RequestAdmin(admin.ModelAdmin):
#     list_display = ['full_name', 'lc', 'position', 'role',
#                   'ep_name', 'ep_entity', 'ep_email','ep_lc','ep_id','opp_id',
#                   'requested_break','program','request_Reason',
#                   "timestamp","updated"]
#     form = RequestForm
#     class Meta:
#         model = Request
#
#
# admin.site.register(Request)

illuminate/forms/apps.py
from django.apps import AppConfig


class ComplaintsConfig(AppConfig):
    name = 'illuminate.forms'

illuminate/forms/population_script.py
from illuminate.forms.create_token import GIS
from illuminate.forms.models import Position, Role, Office
import requests


def delete_everything():

    Position.objects.all().delete()
    print("Positions Deleted")
    Role.objects.all().delete()
    print("Roles Deleted")
    Office.objects.all().delete()
    print("Offices Deleted")
    # Standard.objects.all().delete()
    # print("Standards Deleted")


# def populate_standards():
#
#     Standard(name='Personal Goal Setting', number='1').save()
#     Standard(name='Outgoing Preparation Seminar', number='2').save()
#     Standard(name='Expectation Setting', number='3').save()
#     Standard(name='Incoming Preparation Seminar', number='4').save()
#     Standard(name='Development Spaces', number='5').save()
#     Standard(name='Debrief With AIESEC Home', number='6').save()
#     Standard(name='Visa And Work Permit Information', number='7').save()
#     Standard(name='Arrival Pickup', number='8').save()
#     Standard(name='Departure Support', number='9').save()
#     Standard(name='Job Description Information', number='10').save()
#     Standard(name='Duration', number='11').save()
#     Standard(name='Working Hours', number='12').save()
#     Standard(name='First Day of Work', number='13').save()
#     Standard(name='Insurance', number='14').save()
#     Standard(name='Accommodation', number='15').save()
#     Standard(name='Basic Living Cost', number='16').save()
#
#     print("Standards Populated")
#

def populate_positions():

    Position(name='MCP').save()
    Position(name='MCVP').save()
    Position(name='LCP').save()
    Position(name='LCVP').save()
    Position(name='NST').save()
    Position(name='Team Leader').save()
    Position(name='Coordinator').save()
    Position(name='Member').save()
    print("Positions Populated")


def populate_role():

    Role(name='IGV').save()
    Role(name='IGE').save()
    Role(name='IGT').save()
    Role(name='OGV').save()
    Role(name='OGE').save()
    Role(name='OGT').save()
    Role(name='F&L').save()
    Role(name='TM').save()
    Role(name='IM').save()
    Role(name='Marketing').save()
    Role(name='PD').save()
    print("Roles Populated")


def populate_offices():
    print("Populaing Offices...")
    id = "1609"
    call = GIS()
    access_token = call.generate_token()
    print(access_token)
    url = 'https://gis-api.aiesec.org/v2/committees/' + id + '.json?access_token=' + access_token
    r = requests.get(url).json()
    for i in range(0, 23):
        name = r['suboffices'][i]['name']
        office_id = r['suboffices'][i]['id']
        Office(office_name=name).save()
        Office(office_id=office_id).save()
    print("Offices Populated")


def populate_all():

    populate_role()
    populate_positions()
    populate_offices()
    # populate_standards()


populate_all()

illuminate/analytics/views.py
from django.shortcuts import render, redirect
import django.db.models
from illuminate.forms.models import *

def user_anlaytics(request):

    # initiation data
    offices = Office.objects.order_by('office_name')
    current_user = request.user
    current_user_manager = request.user.manager
    total_tickets = Ticket.objects.all()
    team_tickets = total_tickets.filter(ecb_responsible__manager__name=current_user_manager)
    user_tickets = total_tickets.filter(ecb_responsible=current_user)

    # total absolute numbers
    total_tickets_count = total_tickets.count()
    total_complaints_count = total_tickets.filter(ticket_type='Complaint').count()
    total_requests_count = total_tickets.filter(ticket_type='Request').count()
    total_cases_count = total_tickets.filter(ticket_type='Case').count()


    # Team absolute numbers
    team_tickets_count = team_tickets.count()
    team_complaints_count = team_tickets.filter(ticket_type='Complaint').count()
    team_requests_count = team_tickets.filter(ticket_type='Request').count()
    team_cases_count = team_tickets.filter(ticket_type='Case').count()


    # user absolute numbers
    user_tickets_count = user_tickets.count()
    user_complaints_count = user_tickets.filter(ticket_type='Complaint').count()
    user_complaints_count_open = user_tickets.filter(ticket_type='Complaint', ticket_state='Open').count()
    user_complaints_count_in_progress = user_tickets.filter(ticket_type='Complaint', ticket_state='In Progress').count()
    user_complaints_count_closed = user_tickets.filter(ticket_type='Complaint', ticket_state='Closed').count()

    user_requests_count = user_tickets.filter(ticket_type='Request').count()
    user_requests_count_open = user_tickets.filter(ticket_type='Request', ticket_state='Open').count()
    user_requests_count_in_progress = user_tickets.filter(ticket_type='Request', ticket_state='In Progress').count()
    user_requests_count_closed = user_tickets.filter(ticket_type='Request', ticket_state='Closed').count()

    user_cases_count = user_tickets.filter(ticket_type='Case').count()
    user_cases_count_open = user_tickets.filter(ticket_type='Case', ticket_state='Open').count()
    user_cases_count_in_progress = user_tickets.filter(ticket_type='Case', ticket_state='In Progress').count()
    user_cases_count_closed = user_tickets.filter(ticket_type='Case', ticket_state='Closed').count()

    # user relative numbers
    # total_Complaint_contribution = (user_complaints_count/total_complaints_count)*100


    context = {
        "offices": offices,
        "current_user": current_user,
        "current_user_manager": current_user_manager,
        "tickets": total_tickets,
        "user_tickets": user_tickets,

        # total absolute numbers
        "total_tickets_count": total_tickets_count,
        "total_complaints_count": total_complaints_count,
        "total_requests_count": total_requests_count,
        "total_cases_count": total_cases_count,

        # Team absolute numbers
        "team_tickets_count": team_tickets_count,
        "team_complaints_count": team_complaints_count,
        "team_requests_count": team_requests_count,
        "team_cases_count": team_cases_count,

        # user absolute numbers
        "user_tickets_count": user_tickets_count,

        "user_complaints_count": user_complaints_count,
        "user_complaints_count_open": user_complaints_count_open,
        "user_complaints_count_in_progress": user_complaints_count_in_progress,
        "user_complaints_count_closed": user_complaints_count_closed,

        "user_requests_count": user_requests_count,
        "user_requests_count_open": user_requests_count_open,
        "user_requests_count_in_progress": user_requests_count_in_progress,
        "user_requests_count_closed": user_requests_count_closed,

        "user_cases_count": user_cases_count,
        "user_cases_count_open": user_cases_count_open,
        "user_cases_count_in_progress": user_cases_count_in_progress,
        "user_cases_count_closed": user_cases_count_closed,

        # "total_Complaint_contribution": total_Complaint_contribution,

    }

    return render(request, 'analytics/user_analytics.html', context=context)


def lc_analytics(request, office_name):
    tickets = Ticket.objects.all()
    # complaints = Ticket.objects.filter(ticket_type='Complaint')
    # my_lc = Office.objects.get(pk=office_name)
    # lc = OfficeSnapshot.objects.get(office=my_lc)
    #
    offices = Office.objects.order_by('office_name')

    my_lc = Office.objects.get(pk=office_name)

    lc = Office.objects.get(office_name=my_lc)
    lc_name = my_lc.office_name
    lc_complaints_count = Ticket.objects.filter(ticket_type='Complaint', office__office_name=office_name).count()

    context = {
        "offices": offices,
        "lc_complaints_count": lc_complaints_count,
        "lc_name": lc_name,
        "lc": lc,
        "my_lc": my_lc,
        # "office": office,
    }

    return render(request, "analytics/lc_analytics.html", context)


def home_view(request):

    if request.user.is_authenticated():

        offices = Office.objects.order_by('office_name')
        tickets = Ticket.objects.all()

        current_user = request.user

        user = Ticket.objects.filter(ecb_responsible=current_user)

        # complaints data
        user_complaints_count = tickets.filter(ticket_type='Complaint').count()
        user_complaints_count_open = tickets.filter(ticket_type='Complaint', ticket_state='Open').count()
        user_complaints_count_in_progress = tickets.filter(ticket_type='Complaint', ticket_state='In Progress').count()
        user_complaints_count_closed = tickets.filter(ticket_type='Complaint', ticket_state='Closed').count()

        # requests data
        user_requests_count = tickets.filter(ticket_type='Request').count()
        user_requests_count_open = tickets.filter(ticket_type='Request', ticket_state='Open').count()
        user_requests_count_in_progress = tickets.filter(ticket_type='Request', ticket_state='In Progress').count()
        user_requests_count_closed = tickets.filter(ticket_type='Request', ticket_state='Closed').count()

        # cases data
        user_cases_count = tickets.filter(ticket_type='Case').count()
        user_cases_count_open = tickets.filter(ticket_type='Case', ticket_state='Open').count()
        user_cases_count_in_progress = tickets.filter(ticket_type='Case', ticket_state='In Progress').count()
        user_cases_count_closed = tickets.filter(ticket_type='Case', ticket_state='Closed').count()

        context = {
            "offices": offices,
            "tickets": tickets,
            "user_complaints_count": user_complaints_count,
            "user_requests_count": user_requests_count,
            "user_cases_count": user_cases_count,

            "user_complaints_count_open": user_complaints_count_open,
            "user_complaints_count_in_progress": user_complaints_count_in_progress,
            "user_complaints_count_closed": user_complaints_count_closed,
            "user_requests_count_open": user_requests_count_open,
            "user_requests_count_in_progress": user_requests_count_in_progress,
            "user_requests_count_closed": user_requests_count_closed,
            "user_cases_count_open": user_cases_count_open,
            "user_cases_count_in_progress": user_cases_count_in_progress,
            "user_cases_count_closed": user_cases_count_closed,
        }

        return render(request, "pages/home.html", context)
    else:
        return redirect("accounts/login")

illuminate/core/views.py
from django.shortcuts import render

illuminate/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView
from requests import request
from .models import User
from django.shortcuts import render


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', 'number', 'position', 'sector', 'image']

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):

        model = User

        # These next two lines tell the view to index lookups by username
        slug_field = 'username'
        slug_url_kwarg = 'username'

illuminate/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

illuminate/templates/complaint.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}


<dev class="row">
<div class="col-sm-6 col-sm-offset-3">
{% if title %}
<h1 class="text-align-center">{{ title }}</h1>
{% endif %}
<form method="post" action="">{% csrf_token %}
  {{ complaintform |crispy }}

<input class='btn btn-primary' type="submit" value="submit" />
</form>
</div>
</dev>

{% endblock %}

illuminate/templates/index.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}illuminate{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}

    <!-- Latest compiled and minified Bootstrap 4 beta CSS -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

    <!-- This file stores project-specific CSS -->

    <link href="{% static 'css/project.css' %}" rel="stylesheet">


    {% endblock %}

  </head>

  <body>

    <div class="m-b-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">illuminate</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">Forms</a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'form:create_request' %}">Request</a>
                  <a class="dropdown-item" href="{% url 'form:create_complaint' %}">Complain</a>
                  <a class="dropdown-item" href="{% url 'form:create_case' %}">Case</a>
                </div>
              </li>

            {% if request.user.is_authenticated %}

                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">Tickets</a>
                  <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'form:ticket_list' %}">List</a>
                  </div>
              </li>
              <
              <li class="nav-item"><a class="nav-link" href="{% url 'users:list' %}">{% trans "Users List" %}</a>
              </li>
              <li class="nav-item"><a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item"><a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item"><a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item"><a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}


    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}

      <!-- Required by Bootstrap v4 beta -->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->


      <!-- place project specific Javascript in this file -->

      <script src="{% static 'js/project.js' %}"></script>


    {% endblock javascript %}
  </body>
</html>

illuminate/templates/request.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}


<dev class="row">
<div class="col-sm-6 col-sm-offset-3">
{% if title %}
<h1 class="text-align-center">{{ title }}</h1>
{% endif %}
<form method="post" action="">{% csrf_token %}
  {{ requestform |crispy }}

<input class='btn btn-primary' type="submit" value="submit" />
</form>
</div>
</dev>

{% endblock %}